#!/usr/bin/env node
/**
 * @see http://cjohansen.no/en/node_js/unit_testing_node_js_apps
 */
require.paths.push(__dirname);
require.paths.push(__dirname + '/deps');
require.paths.push(__dirname + '/lib');
process.chdir(__dirname);

require('nodeunit').reporters.default.run(['test']);